# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    body_listener: true
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener: force
    view:
        view_response_listener: true
        formats:
            json: true
            xml: false
            rss: false
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
